name: Docker

on: workflow_dispatch

jobs:
   build-container:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: echo $GITHUB_TOKEN | docker login https://docker.pkg.github.com -u akheron --password-stdin

      - working-directory: ci
        run: docker build -t docker.pkg.github.com/akheron/postres/postgres-for-test:latest .

      - working-directory: ci
        run: docker push docker.pkg.github.com/akheron/postres/postgres-for-test:latest
